// apps/react-app/src/app/app.tsx
import './app.module.scss';
import { AppHeader, AppFooter, BannerSection, SiteContent, QuoteForm, SideDrawer, SearchModal } from '../app/components/custom/components';
import {
  BRAND_NAME,
  HEADER_PHONE,
  COMPANY_NAME,
  FOOTER_PHONE,
  FOOTER_LINKS,
  SOCIAL_LINKS,
  SIDE_DRAWER_SECTIONS,
  FORM_TITLE,
  FORM_INTRO,
  REQUIRED_LABEL,
  CONSENT_PARAGRAPHS,
  STATE_OPTIONS,
  ZIP_PATTERN,
  PHONE_PATTERN,
  BREADCRUMBS,
  CONTENT_PARAGRAPHS_DATA,
  BANNER_HEADING
} from '@apps-shared/lib/constants';

export function App() {
  return (
    <>
      <AppHeader brandName={BRAND_NAME} phone={HEADER_PHONE} />
      <BannerSection heading={BANNER_HEADING} />
      <SideDrawer sections={SIDE_DRAWER_SECTIONS} />
      <SearchModal />
      <SiteContent breadcrumbs={BREADCRUMBS} paragraphs={CONTENT_PARAGRAPHS_DATA}>
        <QuoteForm
          formTitle={FORM_TITLE}
          intro={FORM_INTRO}
          requiredLabel={REQUIRED_LABEL}
          consentParagraphs={CONSENT_PARAGRAPHS}
          states={STATE_OPTIONS}
          zipPattern={ZIP_PATTERN}
          phonePattern={PHONE_PATTERN}
        />
      </SiteContent>
      <AppFooter companyName={COMPANY_NAME} phone={FOOTER_PHONE} links={FOOTER_LINKS} socialLinks={SOCIAL_LINKS} />
    </>
  );
}

export default App;

// apps/angular-app/src/app/app.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, ViewEncapsulation } from '@angular/core';
import { RouterModule } from '@angular/router';
import { CustomComponentsModule } from './custom-components.module';
import {
  BRAND_NAME,
  HEADER_PHONE,
  HEADER_LINKS,
  COMPANY_NAME,
  FOOTER_PHONE,
  FOOTER_LINKS,
  SOCIAL_LINKS,
  SIDE_DRAWER_SECTIONS,
  FORM_TITLE,
  FORM_INTRO,
  REQUIRED_LABEL,
  CONSENT_PARAGRAPHS,
  STATE_OPTIONS,
  ZIP_PATTERN,
  PHONE_PATTERN,
  BREADCRUMBS,
  CONTENT_PARAGRAPHS_DATA,
  BANNER_HEADING,
} from '@apps-shared/lib/constants';

@Component({
  standalone: true,
  imports: [RouterModule, CustomComponentsModule],
  selector: 'app-root',
  templateUrl: './app.html',
  styleUrl: './app.scss',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  encapsulation: ViewEncapsulation.None,
})
export class App {
  protected title = 'angular-app';

  protected bannerHeading = BANNER_HEADING;
  protected brandName = BRAND_NAME;
  protected headerPhone = HEADER_PHONE;
  protected headerLinks = HEADER_LINKS;
  protected companyName = COMPANY_NAME;
  protected footerPhone = FOOTER_PHONE;
  protected footerLinks = FOOTER_LINKS;
  protected socialLinks = SOCIAL_LINKS;
  protected sideDrawerSections = SIDE_DRAWER_SECTIONS;
  protected formTitle = FORM_TITLE;
  protected formIntro = FORM_INTRO;
  protected requiredLabel = REQUIRED_LABEL;
  protected consentParagraphs = CONSENT_PARAGRAPHS;
  protected stateOptions = STATE_OPTIONS;
  protected zipPattern = ZIP_PATTERN;
  protected phonePattern = PHONE_PATTERN;
  protected breadcrumbs = BREADCRUMBS;
  protected contentParagraphs = CONTENT_PARAGRAPHS_DATA;
}
